### PR TITLE
feat: authentication added

### PR DESCRIPTION
**Pull request by Rishabh-078**
features:
a. Login page added
login

b. SignUp page added
signup

c. Logout Button added to Wishlist and Cart Page
logout-btn

style: wishlist button added to the card components

Added anchor links to all pages and did some styling changes, that resulted in increased line of code

### CODE REVIEW

**Review by gauravsinhaweb — APPROVED** [review]
Good to merge. UI looks good.

**Comment by kgajriaAgarwal** [comment]
image
try to make it responsive

**Comment by kgajriaAgarwal** [comment]
else everything is good can be merged!

**Comment by Rishabh-078** [comment]
> image try to make it responsive

I haven't added responsiveness yet will incorporate it later.

**Pull request merged**
